<?php
// we need to give each map a image

$array_map_img = array(

'0' => 'images/minimap/minimap-bra.png',
'1' => 'images/minimap/minimap-n-ares.png',
'2' => 'images/minimap/minimap-norak.png',
'3' => 'images/minimap/minimap_deneb.png',
'4' => 'images/minimap/minimap-e-ares.png',
'5' => 'images/minimap/minimap-hai.png',
'6' => 'images/minimap/minimap-parca.png',
'7' => 'images/minimap/minimap-loa.png',
'8' => 'images/minimap/minimap-morte_n.png',
'9' => 'images/minimap/minimap-morte_w.png',
'10' => 'images/minimap/minimap-castor.png',
'11' => 'images/minimap/minimap-crevasse.png',
'12' => 'images/minimap/minimap-crespo.png',
'13' => 'images/minimap/minimap-draco.png',
'14' => 'images/minimap/minimap-castor_2.png',
'15' => 'images/minimap/minimap-castor_2.png',
'16' => 'images/minimap/minimap-prison.png',
'17' => 'images/minimap/minimap_requies.png',
'18' => 'images/minimap/minimap_avalon.png',
'19' => 'images/minimap/minimap_python.png',
'20' => 'images/minimap/minimap_python-below.png',
'21' => 'images/minimap/minimap_python-below_2.png',
'22' => 'images/minimap/minimap_arena.png',
'23' => 'images/minimap/minimap-warfare.png',
'24' => '', //24_infinitehunt
'25' => '', //25_crespotreasure
'26' => 'images/minimap/minimap-undersea.png',
'27' => 'images/minimap/minimap-conscript_a.png',
'28' => 'images/minimap/minimap-conscript_m.png',
'29' => '', //29_seal
'30' => '', //30_infinitehunt_b
'31' => '', //31_infinitehunt_c
'32' => 'images/minimap/minimap-indun_02.png', 
'33' => 'images/minimap/minimap-indun_02.png', //should be the same as map 32
'34' => '', //34_infinitehunt_s
'35' => 'images/minimap/minimap-nunvice-01.png',
'36' => 'images/minimap/minimap-nunvice-02.png',
'37' => 'images/minimap/minimap-nunvice-03.png',
'38' => 'images/minimap/minimap-transport-ship.png', //38_karon_ship
'39' => 'images/minimap/minimap-dead-front.png', 
'40' => 'images/minimap/minimap-dead-front.png',
'41' => 'images/minimap/minimap-dead-front.png',
'42' => 'images/minimap/minimap-dead-front.png',
'43' => 'images/minimap/minimap-dead-front.png',
'44' => 'images/minimap/minimap-dead-front.png',
'45' => 'images/minimap/minimap-chain-of-fire.png',
'46' => 'images/minimap/minimap-highland.png',
'47' => 'images/minimap/minimap-pilgrimage.png',
'48' => 'images/minimap/minimap-pilgrimage_q.png',
'49' => 'images/minimap/minimap-cherubim.png',
'50' => 'images/minimap/minimap-cherubim_base.png',
'51' => 'images/minimap/minimap-transportship_base.png',
'52' => 'images/minimap/minimap-transport-ship.png',
'53' => 'images/minimap/minimap-transport-ship.png',
'54' => 'images/minimap/minimap-transport-ship.png',
'55' => 'images/minimap/minimap-transport-ship.png',
'56' => 'images/minimap/minimap_arena.png',
'57' => 'images/minimap/minimap_arena-draco.png',
'58' => 'images/minimap/minimap_arena-prison.png',
'59' => 'images/minimap/minimap_arena-norak.png',
'60' => 'images/minimap/minimap-dead-front.png',
'61' => 'images/minimap/minimap-bra-agency.png',
'62' => 'images/minimap/minimap-loa-agency.png',
'63' => 'images/minimap/minimap_dead_land.png',
'64' => 'images/minimap/minimap_dead_land_boss.png',
'65' => 'images/minimap/minimap-pilgrimage_indun.png',
'66' => '', //66_awaken
'67' => 'images/minimap/minimap-egutt.png',
'68' => 'images/minimap/minimap-egutt_base.png',
'69' => 'images/minimap/minimap-egutt_base_b.png',
'70' => '', //70_avalon_b
'71' => 'images/minimap/minimap-under_crespo.png',
'72' => '', //72_under_crespo_1
'73' => '', //73_under_crespo_2
'74' => '', //74_under_crespo_3
'75' => '' //75_under_crespo_4
						
);