<?php

$INSERT[] = "SET IDENTITY_INSERT gallery_form_fields ON";
$INSERT[] = "INSERT INTO gallery_form_fields(id, name, description, type, content, required, position, deleteable) VALUES (1, 'Caption', '', 'text', '', 1, 2, 0);";
$INSERT[] = "INSERT INTO gallery_form_fields(id, name, description, type, content, required, position, deleteable) VALUES (2, 'Description', '', 'text', '', 1, 3, 0);";
$INSERT[] = "INSERT INTO gallery_form_fields(id, name, description, type, content, required, position, deleteable) VALUES (3, 'Image to upload', '', 'file', '', 1, 5, 0);";
$INSERT[] = "INSERT INTO gallery_form_fields(id, name, description, type, content, required, position, deleteable) VALUES (4, 'Upload File', '', 'sepr', '', 0, 4, 0);";
$INSERT[] = "INSERT INTO gallery_form_fields(id, name, description, type, content, required, position, deleteable) VALUES (5, 'Photo Information', '', 'sepr', '', 0, 1, 0);";
$INSERT[] = "SET IDENTITY_INSERT gallery_form_fields OFF";


$INSERT[] = "INSERT INTO gallery_categories (parent, name, description, c_order, images, comments, perms_thumbs, perms_view, perms_images, perms_comments, perms_moderate, allow_ibfcode, allow_html, password, approve_images, imgs_per_col, imgs_per_row, watermark_images, thumbnail, allow_comments, approve_comments, inc_post_count, status, last_pic_id, def_view, rate, allow_movies, allow_images, category_only, album_mode, last_pic_name, last_member_id, mod_images, cat_rule_method, cat_rule_title, cat_rule_text, mem_gallery, last_pic_date, name_seo, cover_img_id, images_per_page) VALUES (0, 'Members Gallery', 'This is a collection of all our member''s albums.', 1, 0, 0, '1,2,3,4', '1,2,3,4', '', '', '4', 1, 0, '', 0, 5, 5, 1, 1, 1, 1, 1, 1, 0, 'idate:DESC:*', 1, 1, 1, 1, 1, '', 0, 0, 0, '', '', 'a:2:{s:18:\"mem_display_method\";s:1:\"1\";s:18:\"mem_image_location\";s:1:\"0\";}', 0, 'members-gallery', 0, 25);";
$INSERT[] = "INSERT INTO permission_index ( app, perm_type, perm_type_id, perm_view, perm_2, perm_3, perm_4, perm_5, perm_6, perm_7, owner_only, friend_only, authorized_users) VALUES( 'gallery', 'cat', 1, '*', '*', ',4,3,6,', ',4,3,6,', ',4,6,', '', '', 0, 0, NULL);";

$INSERT[] = "INSERT INTO gallery_media_types (icon, title, mime_type, extension, allowed, allow_user_thumb, display_code, default_type) VALUES('quicktime.gif', 'Quicktime Movie', 'video/quicktime', '.mov', 1, 0, '&lt;embed autoplay=&quot;true&quot; showcontrols=&quot;true&quot; showstatusbar=&quot;true&quot; showtracker=&quot;true&quot; src=&quot;{FILE}&quot; width=&quot;320&quot; height=&quot;240&quot;&gt;', 0);";
$INSERT[] = "INSERT INTO gallery_media_types (icon, title, mime_type, extension, allowed, allow_user_thumb, display_code, default_type) VALUES('win_player.gif', 'Windows Media Player', 'video/x-ms-wmv', '.wmv', 1, 1, '&lt;embed autoplay=&quot;true&quot; showcontrols=&quot;true&quot; showstatusbar=&quot;true&quot; showtracker=&quot;true&quot; src=&quot;{FILE}&quot; width=&quot;320&quot; height=&quot;240&quot;&gt;', 0);";
$INSERT[] = "INSERT INTO gallery_media_types (icon, title, mime_type, extension, allowed, allow_user_thumb, display_code, default_type) VALUES('gif.gif', 'JPEG', 'image/jpeg', '.jpg,.jpeg', 1, 0, '<#IMAGE#>', 1);";
$INSERT[] = "INSERT INTO gallery_media_types (icon, title, mime_type, extension, allowed, allow_user_thumb, display_code, default_type) VALUES('gif.gif', 'PNG', 'image/png', '.png', 1, 0, '<#IMAGE#>', 1);";
$INSERT[] = "INSERT INTO gallery_media_types (icon, title, mime_type, extension, allowed, allow_user_thumb, display_code, default_type) VALUES('gif.gif', 'GIF', 'image/gif', '.gif', 1, 0, '<#IMAGE#>', 1);";
$INSERT[] = "INSERT INTO gallery_media_types (icon, title, mime_type, extension, allowed, allow_user_thumb, display_code, default_type) VALUES('win_player.gif', 'MPEG', 'video/mpeg', '.mpg, .mpeg', 1, 0, '&lt;embed src=&quot;{FILE}&quot; width=&quot;320&quot; height=&quot;240&quot; autostart=&#39;true&#39;&gt;', 0);";
$INSERT[] = "INSERT INTO gallery_media_types (icon, title, mime_type, extension, allowed, allow_user_thumb, display_code, default_type) VALUES('win_player.gif', 'AVI', 'video/x-ms-asf', '.avi', 1, 0, '&lt;embed src=&quot;{FILE}&quot; width=&quot;320&quot; height=&quot;240&quot; name=&quot;Player&quot; animationatStart=&quot;1&quot; quality=&quot;high&quot; SendOpenStateChangeEvents=&quot;1&quot; align=&quot;middle&quot; uimode=&quot;1&quot; showstatusbar=&quot;1&quot; showControls=&quot;0&quot; type=&quot;application/x-mplayer2&quot; pluginspage=&quot;http://activex.microsoft.com/activex/controls/mplayer/&quot;&gt;', 0);";
$INSERT[] = "INSERT INTO gallery_media_types (icon, title, mime_type, extension, allowed, allow_user_thumb, display_code, default_type) VALUES('flash.gif', 'Flash', 'application/x-shockwave-flash', '.swf', 1, 1, '&lt;object width=&quot;550&quot; height=&quot;400&quot;&gt;\n&lt;param name=&quot;movie&quot; value=&quot;{FILE}&quot;&gt;\n&lt;embed src=&quot;{FILE}&quot; width=&quot;550&quot; height=&quot;400&quot;&gt;\n&lt;/embed&gt;\n&lt;/object&gt;', 0);";

$INSERT[] = <<<EOF
INSERT INTO rc_classes (onoff, class_title, class_desc, author, author_url, pversion, my_class, group_can_report, mod_group_perm, extra_data, lockd, app) VALUES(1, 'Gallery Plugin', 'This is the plugin for making reports for the <a href=''http://www.invisiongallery.com/'' target=''_blank''>IP.Gallery</a>.', 'Invision Power Services, Inc', 'http://invisionpower.com', 'v1.0', 'gallery', ',1,2,3,4,6,', ',4,6,', 'a:2:{s:15:"report_supermod";s:1:"1";s:13:"report_bypass";s:1:"1";}', 0, 'gallery');
EOF;

