<?php
// we need to give each map a image
// This map list is made on the maplist.csv from dekaron from gamehi

// Date wensday 15 december 2010, 12:36:05
// Version 2.0
// VERSION,EU-18.0.3

$array_map = array(

'0'=>"Braiken Castle",
'1'=>"North Ares",
'2'=>"Den of Norak",
'3'=>"Denebe",
'4'=>"East Ares",
'5'=>"Heiharp",
'6'=>"Parca Temple",
'7'=>"Loa Castle",
'8'=>"North Morte",
'9'=>"West Morte",
'10'=>"Castor Cave",
'11'=>"Frozen Hell",
'12'=>"Crespo",
'13'=>"Draco Desert",
'14'=>"Norak Cave 2nd Fl.",
'15'=>"Castor Cave 2nd Fl.",
'16'=>"Braiken Castle Underground Prison",
'17'=>"Requies Beach",
'100'=>"Knight Selection Map",
'101'=>"Hunter Selection Map",
'102'=>"Magician Selection Map",
'103'=>"Summoner Selection Map",
'104'=>"Healer Selection Map",
'105'=>"Login",
'106'=>"Bagi Selection Map",
'107'=>"Aloken Selection Map",
'18'=>"Avalon Island",
'19'=>"Python Castle",
'20'=>"Tomb of the Black Dragon",
'21'=>"Cursed Maze",
'22'=>"Undo Stadium",
'23'=>"Genoa Castle",
'24'=>"Magic Field of Crevice C",
'25'=>"Treasure of Crespo C",
'26'=>"Aquarius",
'27'=>"Rookie Maze",
'28'=>"Rookie Maze",
'29'=>"Cave of Abyss",
'30'=>"Magic Field of Crevice B",
'31'=>"Magic Field of Crevice A",
'32'=>"Treasure of Crespo B",
'33'=>"Treasure of Crespo A",
'34'=>"Magic Field of Crevice:Depth",
'35'=>"The Temple of Nunvice",
'36'=>"The Temple of Nunvice",
'37'=>"The Temple of Nunvice",
'39'=>"Dead Front [Doom]",
'40'=>"Dead Front [Common]",
'41'=>"Dead Front [Baron]",
'42'=>"Dead Front [Earl]",
'43'=>"Dead Front [Duke]",
'44'=>"Dead Front [Arc]",
'45'=>"Chain of Fire",
'46'=>"Acquirai Ruins",
'47'=>"Space of Pilgrimage",
'48'=>"Quilue Rihanna",
'49'=>"Nest of Cherubim",
'50'=>"Morse Yalawai",
'51'=>"The Qualines",
'52'=>"Transport Ship of Karon-C",
'53'=>"Transport Ship of Karon-B",
'54'=>"Transport Ship of Karon-A",
'55'=>"Transport Ship of Karon-S",
'56'=>"Undo Stadium",
'57'=>"Oasis Kartell",
'58'=>"Norak Secret Arena",
'59'=>"Helicita Colosseum",
'60'=>"Dead Front [Doom]",
'61'=>"Braiken Agency",
'62'=>"Exchange Center",
'63'=>"Death Land",
'64'=>"Death Land Boss",
'65'=>"Plane Of Pilgrimage Indun",
'66'=>"Death Land Indun",
'67'=>"Egutt",
'68'=>"Egutt Base",
'69'=>"Egutt Base B",
'88'=>"Tower Base",
'89'=>"Tower Dungeon A",
'90'=>"Tower Dungeon B",
'91'=>"Tower Dungeon C",
'92'=>"Tower Dungeon D",
'93'=>"Tower Dungeon E",
'150'=>"Ardeca",
'152'=>"Sacred Claw",
'153'=>"Prison Arena",
'154'=>"Draco Arena",
'155'=>"Norak Arena",
'156'=>"Ark Arcana",
'157'=>"Phantom Land",
'158'=>"Shrine of Elonohm",
'159'=>"Elonohm Raid",
'177'=>"Pyhton Castle Inside",
'181'=>"Dravis Under",
'182'=>"Salvation Village",
'183'=>"Dravis Field",
'184'=>"Sacred Claw",
'65535'=>"Settings for Map Tool"
						
);
?>